# Generated by Django 4.1.3 on 2022-11-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KASIR', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='salesItems',
            new_name='ItemPenjualan',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Kategori',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Penjualan',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Produk',
        ),
    ]
